from __future__ import annotations

import argparse
import hashlib
import json
import math
from collections import Counter
from typing import Any

from ticket30_potential_synthesis_lab import ROOT, read_json, v2, write_json


GENERATED_AT = "2026-07-17T01:20:00+09:00"
SCHEMA = "primeproject.ticket126-route-correction-audit.v1"
PREREGISTRATION_SCHEMA = (
    "primeproject.ticket126-route-correction-preregistration.v1"
)
PREREGISTRATION_COMMIT = "b7d5fb6bc10583d0243c66b41ea4cab315f40738"
RECOVERY_PREREGISTRATION_COMMIT = (
    "669b28ad8278844f9e9c1d9b2281a3582b3772d3"
)
GOLDBACH_VERIFIED_LIMIT = 4_000_000_000_000_000_000
PRIMARY_ENDPOINT_TOLERANCE = 1e-12
GRAM_RECONSTRUCTION_TOLERANCE = 1e-7


def canonical_sha256(payload: Any) -> str:
    encoded = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def preregistration_contract() -> dict[str, Any]:
    payload = read_json(
        ROOT
        / "data/open-problem/ticket126-route-correction-preregistration.json"
    )
    if payload.get("schema") != PREREGISTRATION_SCHEMA:
        raise ValueError("TICKET126 preregistration schema changed")
    twin = payload.get("twin_prime", {})
    if int(twin.get("holdout_horizon", -1)) != 33_554_432:
        raise ValueError("TICKET126 holdout horizon changed")
    if float(twin.get("alpha", -1.0)) != 0.75:
        raise ValueError("TICKET126 alpha changed")
    if float(twin.get("beta", -1.0)) != 0.23:
        raise ValueError("TICKET126 beta changed")
    policy = twin.get("execution_policy", {})
    if int(policy.get("runs", -1)) != 1:
        raise ValueError("TICKET126 execution count changed")
    if bool(policy.get("retuning_after_result", True)):
        raise ValueError("TICKET126 permits post-result retuning")
    return payload


def riemann_autocorrelation_cone_audit() -> dict[str, Any]:
    sample_vectors = [
        [-2, -1, 0, 1, 2],
        [1, -3, 2, 0],
        [0, 0, 0],
        [5],
    ]
    sample_rows = []
    for vector in sample_vectors:
        identity_value = sum(value * value for value in vector)
        sample_rows.append(
            {
                "vector": vector,
                "autocorrelation_identity_value": identity_value,
                "nonnegative": identity_value >= 0,
            }
        )
    return {
        "theorem_name": "ContinuousEvaluationSeparatesAutocorrelationCone",
        "setting": (
            "Let V be a real topological test-function space on a group with "
            "continuous evaluation ell(h)=h(e) at the identity. Let C be the "
            "convex cone generated by real autocorrelations g*tilde(g)."
        ),
        "proved_statement": (
            "If V contains f with f(e)<0, then C is not dense in V."
        ),
        "proof": (
            "For every generator h=g*tilde(g), h(e)=integral |g|^2>=0. "
            "Hence C lies in the closed half-space ell>=0. Any f with ell(f)<0 "
            "has an open neighborhood disjoint from C, so f is not in closure(C)."
        ),
        "route_decision": {
            "discard": (
                "Using density of the autocorrelation cone in the full real test "
                "space to invoke TICKET125's extension lemma."
            ),
            "retain": (
                "Prove Weil positivity directly for every admissible "
                "autocorrelation satisfying the exact moment constraints."
            ),
            "next_theorem": "NonCircularWeilAutocorrelationPositivity",
        },
        "finite_sanity_rows": sample_rows,
        "machine_audit": {
            "sample_count": len(sample_rows),
            "negative_autocorrelation_identity_count": sum(
                int(not row["nonnegative"]) for row in sample_rows
            ),
            "separating_witness_identity_value": -1,
            "total_failure_count": sum(
                int(not row["nonnegative"]) for row in sample_rows
            ),
        },
        "proof_boundary": (
            "This exact no-go retires one density shortcut. It does not disprove "
            "Weil's criterion and proves neither RH nor a zero off the critical line."
        ),
    }


def _cylinder_certificate(residue: int, bits: int) -> dict[str, Any] | None:
    current = residue
    consumed = 0
    word: list[int] = []
    for step in range(1, bits + 1):
        valuation = v2(3 * current + 1)
        if consumed + valuation >= bits:
            return None
        consumed += valuation
        word.append(valuation)
        current = (3 * current + 1) >> valuation
        if current < residue:
            return {
                "terminal": current,
                "steps": step,
                "consumed_bits": consumed,
                "word": word,
            }
    return None


def collatz_eventually_low_tree_audit(
    minimum_bits: int = 4,
    maximum_bits: int = 28,
) -> dict[str, Any]:
    if minimum_bits < 2 or maximum_bits < minimum_bits:
        raise ValueError("invalid adaptive precision interval")

    frontier: dict[int, int] = {}
    modulus = 1 << minimum_bits
    for residue in range(1, modulus, 2):
        if _cylinder_certificate(residue, minimum_bits) is None:
            frontier[residue] = 0

    rows: list[dict[str, Any]] = []
    source_ticket = read_json(
        ROOT / "data/open-problem/ticket125-infinite-bridge-contracts.json"
    )
    ticket125_rows = {
        int(row["precision_bits"]): row
        for row in source_ticket["infinite_bridge_contracts"][
            "collatz_adaptive_residue_descent"
        ]["precision_rows"]
    }
    ticket125_mismatch_count = 0
    boundary_high_count = 0
    boundary_low_run = 0
    boundary_max_low_run = 0
    previous_boundary: int | None = None

    for bits in range(minimum_bits, maximum_bits + 1):
        modulus = 1 << bits
        if bits > minimum_bits:
            parent_modulus = 1 << (bits - 1)
            next_frontier: dict[int, int] = {}
            low_unresolved = 0
            high_unresolved = 0
            for parent, low_run in frontier.items():
                for high_child in (False, True):
                    child = parent + (parent_modulus if high_child else 0)
                    if _cylinder_certificate(child, bits) is not None:
                        continue
                    if high_child:
                        next_frontier[child] = 0
                        high_unresolved += 1
                    else:
                        next_frontier[child] = low_run + 1
                        low_unresolved += 1
            frontier = next_frontier
        else:
            low_unresolved = len(frontier)
            high_unresolved = 0

        odd_class_count = modulus >> 1
        unresolved_count = len(frontier)
        certified_count = odd_class_count - unresolved_count
        histogram = Counter(frontier.values())
        maximum_low_run = max(frontier.values(), default=0)
        longest_witnesses = sorted(
            residue
            for residue, low_run in frontier.items()
            if low_run == maximum_low_run
        )[:8]

        boundary = (-pow(3, -1, modulus)) % modulus
        if previous_boundary is not None:
            high = boundary != previous_boundary
            if high:
                boundary_high_count += 1
                boundary_low_run = 0
            else:
                boundary_low_run += 1
            boundary_max_low_run = max(
                boundary_max_low_run, boundary_low_run
            )
        previous_boundary = boundary

        row = {
            "precision_bits": bits,
            "odd_class_count": odd_class_count,
            "certified_class_count": certified_count,
            "unresolved_class_count": unresolved_count,
            "unresolved_mass": unresolved_count / odd_class_count,
            "low_child_unresolved_count": low_unresolved,
            "high_child_unresolved_count": high_unresolved,
            "maximum_consecutive_low_refinements": maximum_low_run,
            "longest_low_run_witnesses": longest_witnesses,
            "low_run_histogram": {
                str(run): count for run, count in sorted(histogram.items())
            },
            "boundary_residue": boundary,
            "boundary_first_valuation": v2(3 * boundary + 1),
        }
        rows.append(row)
        prior = ticket125_rows.get(bits)
        if prior is not None:
            ticket125_mismatch_count += int(
                int(prior["unresolved_class_count"]) != unresolved_count
                or int(prior["uniformly_descending_class_count"])
                != certified_count
            )

    last = rows[-1]
    return {
        "theorem_name": "EventuallyLowUnresolvedPathIffFiniteStoppingCounterexample",
        "adaptive_tree_definition": (
            "U_k contains odd residues modulo 2^k for which no accelerated "
            "iterate below the residue is certified before total valuation reaches k."
        ),
        "proved_equivalence": {
            "statement": (
                "A positive odd integer n has no finite stopping descent if and "
                "only if its residue path is an eventually-low infinite path in U_k."
            ),
            "forward_proof": (
                "For k above the bit length of n, the representative of n modulo "
                "2^k is n and every later refinement chooses the low child. If n "
                "never descends, no U_k certificate can remove this path."
            ),
            "reverse_proof": (
                "An eventually-low inverse-limit path is represented by one fixed "
                "positive odd integer n after some level. If n descended after m "
                "accelerated steps consuming S valuation bits, every k>S and above "
                "the bit length of n would certify that descent, contradicting "
                "membership in every later U_k."
            ),
            "collatz_corollary": (
                "By UniversalFiniteStoppingDescentIffCollatz, Collatz is equivalent "
                "to absence of eventually-low infinite paths in the adaptive tree."
            ),
        },
        "boundary_ray_correction": {
            "ray": "r_k=-3^(-1) mod 2^k",
            "proved_fact": (
                "The compatible boundary ray is not eventually low and therefore "
                "is not the residue path of a positive integer. If it stabilized "
                "at n, then 2^k would divide 3n+1 for arbitrarily large k, forcing "
                "3n+1=0."
            ),
            "decision": (
                "Retire the boundary ray as a natural-number obstruction; retain it "
                "only as a no-go for fixed-precision determined-word completeness."
            ),
            "observed_high_refinement_count": boundary_high_count,
            "observed_maximum_low_run": boundary_max_low_run,
        },
        "precision_rows": rows,
        "retained_target": {
            "name": "UniformEventuallyLowPathExclusion",
            "statement": (
                "Prove that every infinite unresolved path has infinitely many high "
                "refinements, or give an independent well-founded rank excluding an "
                "eventually-low tail."
            ),
        },
        "machine_audit": {
            "minimum_precision_bits": minimum_bits,
            "maximum_precision_bits": maximum_bits,
            "largest_odd_class_count": int(last["odd_class_count"]),
            "largest_unresolved_class_count": int(
                last["unresolved_class_count"]
            ),
            "largest_unresolved_mass": float(last["unresolved_mass"]),
            "largest_maximum_low_run": max(
                int(row["maximum_consecutive_low_refinements"])
                for row in rows
            ),
            "ticket125_replay_mismatch_count": ticket125_mismatch_count,
            "total_failure_count": ticket125_mismatch_count,
        },
        "proof_boundary": (
            "The path equivalence is exact and removes a false 2-adic obstruction. "
            "The finite tree through 28 bits does not exclude all eventually-low "
            "paths, so Collatz remains open."
        ),
    }


def _integer_cuberoot(number: int) -> int:
    low = 0
    high = 1
    while high**3 <= number:
        high *= 2
    while low + 1 < high:
        middle = (low + high) // 2
        if middle**3 <= number:
            low = middle
        else:
            high = middle
    return low


def _proper_prime_powers(limit: int) -> set[int]:
    if limit < 4:
        return set()
    prime_limit = math.isqrt(limit)
    sieve = bytearray(b"\x01") * (prime_limit + 1)
    sieve[:2] = b"\x00\x00"
    for prime in range(2, math.isqrt(prime_limit) + 1):
        if sieve[prime]:
            sieve[prime * prime :: prime] = b"\x00" * (
                (prime_limit - prime * prime) // prime + 1
            )
    powers: set[int] = set()
    for prime, flag in enumerate(sieve):
        if not flag:
            continue
        value = prime * prime
        while value <= limit:
            powers.add(value)
            value *= prime
    return powers


def proper_prime_power_count_bound(number: int) -> int:
    if number < 4:
        return 0
    exponent_count = number.bit_length() - 1
    return math.isqrt(number) + max(0, exponent_count - 2) * _integer_cuberoot(
        number
    )


def goldbach_prime_power_contamination_audit(
    verified_limit: int = GOLDBACH_VERIFIED_LIMIT,
) -> dict[str, Any]:
    log_h = math.log(verified_limit)
    log2_h = math.log2(verified_limit)
    decreasing_threshold = math.exp(6.0 + 2.0 * math.log(2.0))
    uniform_b = 2.0 * (
        1.0 + (log2_h - 2.0) * verified_limit ** (-1.0 / 6.0)
    )
    normalized_scale = log_h**2 / math.sqrt(verified_limit)
    contamination_at_h = uniform_b * normalized_scale
    maximum_k_for_a1 = (1.0 - contamination_at_h) * log_h

    count_rows = []
    failure_count = 0
    for limit in (16, 64, 256, 1_000, 10_000, 100_000):
        actual = len(_proper_prime_powers(limit))
        bound = proper_prime_power_count_bound(limit)
        holds = actual <= bound
        failure_count += int(not holds)
        count_rows.append(
            {
                "limit": limit,
                "actual_distinct_proper_prime_power_count": actual,
                "integer_upper_bound": bound,
                "bound_holds": holds,
            }
        )

    return {
        "theorem_name": "ExplicitProperPrimePowerContaminationBound",
        "weighted_sum": "G(N)=sum Lambda(m)Lambda(N-m)",
        "proper_prime_power_part": (
            "P(N) is the sub-sum where at least one of m and N-m is p^a "
            "with p prime and a>=2."
        ),
        "proved_count_bound": {
            "statement": (
                "Q(N)<=sqrt(N)+(floor(log_2 N)-2)N^(1/3), where Q(N) "
                "counts distinct proper prime powers at most N."
            ),
            "proof": (
                "For exponent a=2 there are at most sqrt(N) bases. For each "
                "a=3,...,floor(log_2 N), there are at most N^(1/a)<=N^(1/3) "
                "bases. Summing gives the bound; duplicates only reduce Q(N)."
            ),
        },
        "proved_contamination_bound": {
            "statement": (
                "P(N)<=2*sqrt(N)*log(N)^2*"
                "[1+(log_2 N-2)N^(-1/6)]."
            ),
            "proof": (
                "Each von Mangoldt product is at most log(N)^2. The union of "
                "ordered pairs with a proper prime power in either coordinate has "
                "at most 2Q(N) elements."
            ),
        },
        "uniform_tail": {
            "verified_limit": verified_limit,
            "monotonicity_threshold": decreasing_threshold,
            "proof": (
                "The derivative of (log_2 x-2)x^(-1/6) has the sign of "
                "6+2log(2)-log(x), so it decreases for x>exp(6+2log 2)."
            ),
            "explicit_uniform_B": uniform_b,
            "normalized_contamination_at_H": contamination_at_h,
            "strict_K_ceiling_for_A_1": maximum_k_for_a1,
            "k_40_budget_margin": (
                1.0 - 40.0 / log_h - contamination_at_h
            ),
        },
        "count_sanity_rows": count_rows,
        "route_decision": {
            "closed_premise": "proper-prime-power contamination constant B",
            "remaining_premises": [
                "uniform positive major coefficient A",
                "uniform pointwise residual constant K",
            ],
            "next_theorem": "ExplicitGoldbachMajorAndResidualConstants",
        },
        "machine_audit": {
            "count_sanity_case_count": len(count_rows),
            "verified_limit_above_monotonicity_threshold": (
                verified_limit > decreasing_threshold
            ),
            "explicit_uniform_B": uniform_b,
            "t125_maximum_compatible_B_for_K40": (
                1.0 - 40.0 / log_h
            )
            / normalized_scale,
            "total_failure_count": failure_count,
        },
        "proof_boundary": (
            "The proper-prime-power error is now explicitly controlled and is not "
            "the bottleneck at H=4e18. No positive pointwise major-minus-residual "
            "bound with explicit A and K is proved, so Goldbach remains open."
        ),
    }


def execute_twin_holdout() -> dict[str, Any]:
    from ticket117_twin_dyadic_mobius_endpoint_gram_audit import (
        audit_dyadic_mobius_endpoint_gram,
    )
    from ticket122_twin_canonical_joint_defect_audit import audit_scale
    from ticket124_canonical_obstruction_limsup_criterion import obstruction_row

    preregistration = preregistration_contract()
    recovery = read_json(
        ROOT
        / "data/open-problem/ticket126-holdout-recovery-preregistration.json"
    )
    recovery_contract = recovery.get("recovery_execution", {})
    if float(recovery_contract.get("primary_endpoint_tolerance", -1.0)) != (
        PRIMARY_ENDPOINT_TOLERANCE
    ):
        raise ValueError("TICKET126 recovery primary tolerance changed")
    if float(
        recovery_contract.get("inherited_gram_reconstruction_tolerance", -1.0)
    ) != GRAM_RECONSTRUCTION_TOLERANCE:
        raise ValueError("TICKET126 recovery Gram tolerance changed")
    contract = preregistration["twin_prime"]
    horizon = int(contract["holdout_horizon"])
    row = audit_dyadic_mobius_endpoint_gram(
        horizon,
        None,
        "post_registration_ticket126_32m_holdout",
    )
    joint = audit_scale(
        {
            "selection_status": "preregistered_ticket126_32m",
            "row": row,
        }
    )
    obstruction = obstruction_row(
        float(joint["known_without_type_ii_minor"]),
        float(joint["independent_singleton_budget"]),
        float(joint["boundary_and_variation_budget"]),
        float(joint["exact_total_saving"]),
        float(joint["joint_lower_certificate"]),
    )
    source = read_json(
        ROOT
        / "data/open-problem/ticket124-canonical-obstruction-limsup-criterion.json"
    )["canonical_obstruction_limsup_criterion"]["finite_obstruction_rows"][-1]
    if int(source["horizon"]) != int(contract["source_horizon"]):
        raise ValueError("TICKET126 source horizon changed")
    alpha = float(contract["alpha"])
    beta = float(contract["beta"])
    exact_residual = float(obstruction["canonical_obstruction_exact"]) - (
        alpha * float(source["canonical_obstruction_exact"])
    )
    certificate_residual = float(
        obstruction["canonical_obstruction_certificate"]
    ) - alpha * float(source["canonical_obstruction_certificate"])
    primary_pass = (
        certificate_residual <= beta + PRIMARY_ENDPOINT_TOLERANCE
    )
    primary = {
        "status": (
            "pass_finite_preregistered_transition"
            if primary_pass
            else "fail_frozen_dyadic_contraction_candidate"
        ),
        "from_horizon": int(source["horizon"]),
        "to_horizon": horizon,
        "alpha": alpha,
        "beta": beta,
        "source_exact_obstruction": float(
            source["canonical_obstruction_exact"]
        ),
        "holdout_exact_obstruction": float(
            obstruction["canonical_obstruction_exact"]
        ),
        "exact_recurrence_residual": exact_residual,
        "exact_slack_to_beta": beta - exact_residual,
        "source_certificate_obstruction": float(
            source["canonical_obstruction_certificate"]
        ),
        "holdout_certificate_obstruction": float(
            obstruction["canonical_obstruction_certificate"]
        ),
        "certificate_recurrence_residual": certificate_residual,
        "certificate_slack_to_beta": beta - certificate_residual,
        "primary_endpoint_passes": primary_pass,
    }
    result = {
        "theorem_name": "PreregisteredThirtyTwoMillionDyadicContractionHoldout",
        "preregistration_commit": PREREGISTRATION_COMMIT,
        "preregistration_payload_sha256": canonical_sha256(preregistration),
        "recovery_preregistration_commit": RECOVERY_PREREGISTRATION_COMMIT,
        "recovery_preregistration_payload_sha256": canonical_sha256(recovery),
        "failed_unserialized_execution_count": 1,
        "valid_recovery_execution_count": 1,
        "retuned_after_result": False,
        "primary_result": primary,
        "obstruction_row": {"horizon": horizon, **obstruction},
        "joint_canonical_audit": joint,
        "holdout_row": row,
        "machine_audit": {
            "primary_endpoint_passes": primary_pass,
            "maximum_identity_error": max(
                float(obstruction["exact_identity_error"]),
                float(obstruction["certificate_identity_error"]),
                float(joint["saving_identity_error"]),
                float(joint["canonical_reconstruction_error"]),
            ),
            "total_failure_count": int(
                max(
                    float(obstruction["exact_identity_error"]),
                    float(obstruction["certificate_identity_error"]),
                    float(joint["saving_identity_error"]),
                    float(joint["canonical_reconstruction_error"]),
                )
                > GRAM_RECONSTRUCTION_TOLERANCE
            ),
        },
        "proof_boundary": (
            "This is one preregistered finite 16M-to-32M transition. A pass does "
            "not prove the recurrence on an infinite tail; a failure refutes only "
            "the frozen alpha=3/4, beta=23/100 candidate. Twin Prime remains open."
        ),
    }
    write_json(
        ROOT
        / "data/open-problem/ticket126-twin-32m-first-valid-result.json",
        {
            "schema": SCHEMA,
            "generated_at": GENERATED_AT,
            "status": "first_valid_recovery_result_recorded_before_aggregate_audit",
            "twin_prime": result,
        },
    )
    return result


def _load_committed_twin_holdout() -> dict[str, Any]:
    path = ROOT / "data/open-problem/ticket126-route-correction-audit.json"
    if not path.exists():
        raise ValueError("No committed TICKET126 holdout exists; use --execute-holdout")
    return read_json(path)["route_correction_audit"]["twin_prime"]


def build_audit(twin: dict[str, Any]) -> dict[str, Any]:
    rh = riemann_autocorrelation_cone_audit()
    collatz = collatz_eventually_low_tree_audit()
    goldbach = goldbach_prime_power_contamination_audit()
    sections = (rh, collatz, goldbach, twin)
    return {
        "theorem_name": "FourConjectureRouteCorrectionAndPremiseClosureAudit",
        "source_ticket": "TICKET-125",
        "riemann": rh,
        "collatz": collatz,
        "goldbach": goldbach,
        "twin_prime": twin,
        "literature_boundary": [
            {
                "citation": "Connes and Consani, The Scaling Hamiltonian",
                "url": "https://arxiv.org/abs/1910.14368",
                "role": "Primary Weil-autocorrelation positivity context; the direct all-autocorrelation condition remains open.",
            },
            {
                "citation": "Tao, Almost all orbits of the Collatz map attain almost bounded values",
                "url": "https://arxiv.org/abs/1909.03562",
                "role": "Primary almost-all result; TICKET126 keeps the universal eventually-low path quantifier.",
            },
            {
                "citation": "Oliveira e Silva, Herzog, and Pardi, Empirical verification of the even Goldbach conjecture",
                "url": "https://doi.org/10.1090/S0025-5718-2013-02787-1",
                "role": "Primary finite verification through 4e18 used only after an analytic tail theorem.",
            },
            {
                "citation": "Ford and Maynard, On the theory of prime producing sieves",
                "url": "https://arxiv.org/abs/2407.14368",
                "role": "Primary Type I/II sieve context; the 32M result is finite and supplies no exact-gap theorem.",
            },
        ],
        "machine_audit": {
            "problem_count": 4,
            "exact_new_theorem_count": 3,
            "preregistered_holdout_count": 1,
            "retired_route_count": 2,
            "closed_missing_premise_count": 1,
            "conjecture_resolution_count": 0,
            "total_failure_count": sum(
                int(section["machine_audit"]["total_failure_count"])
                for section in sections
            ),
        },
        "proof_boundary": (
            "TICKET126 proves a RH route no-go, a Collatz path equivalence, and an "
            "explicit Goldbach prime-power bound, and evaluates one preregistered "
            "Twin finite holdout. It proves or refutes none of the four conjectures."
        ),
    }


def build_attempts(audit: dict[str, Any]) -> list[dict[str, Any]]:
    boundary = "No conjecture proof and no certified conjecture counterexample."
    twin_pass = bool(
        audit["twin_prime"]["primary_result"]["primary_endpoint_passes"]
    )
    return [
        {
            "problem_id": "riemann",
            "ticket_id": "RH-TICKET-126",
            "status": "autocorrelation_density_shortcut_refuted_direct_positivity_open",
            "route": "AutocorrelationConeDensityNoGo",
            "proof_or_counterexample_mode": "exact route counterexample by continuous separation",
            "attempt": "Test whether the Weil autocorrelation cone can supply the dense cone required by TICKET125.",
            "bounded_result": {"audit_ref": "riemann"},
            "obstruction": "Continuous identity evaluation confines autocorrelations to a closed half-space, so this cone is not dense in the full real test space.",
            "candidate_theorem": "NonCircularWeilAutocorrelationPositivity",
            "next_experiment": "Work directly on every admissible autocorrelation with the exact two moment constraints; do not invoke density in the full test space.",
            "claim_boundary": boundary,
        },
        {
            "problem_id": "collatz",
            "ticket_id": "CO-TICKET-126",
            "status": "eventually_low_path_equivalence_proved_uniform_exclusion_open",
            "route": "EventuallyLowUnresolvedPathEquivalence",
            "proof_or_counterexample_mode": "contrapositive natural-path classification plus adaptive exact cylinders",
            "attempt": "Separate natural-number paths from generic 2-adic boundary rays and characterize the only infinite paths that could encode a counterexample.",
            "bounded_result": {"audit_ref": "collatz"},
            "obstruction": "No uniform theorem excludes every eventually-low unresolved path beyond the finite 28-bit tree.",
            "candidate_theorem": "UniformEventuallyLowPathExclusion",
            "next_experiment": "Synthesize a rank only for low-child tails and use surviving long low runs as exact counterexamples to each proposed rank.",
            "claim_boundary": boundary,
        },
        {
            "problem_id": "goldbach",
            "ticket_id": "GB-TICKET-126",
            "status": "proper_prime_power_constant_proved_major_residual_constants_open",
            "route": "ExplicitProperPrimePowerContaminationBound",
            "proof_or_counterexample_mode": "direct counting proof closes one analytic premise",
            "attempt": "Prove a uniform explicit B instead of treating proper-prime-power contamination as an unknown fitted constant.",
            "bounded_result": {"audit_ref": "goldbach"},
            "obstruction": "Uniform pointwise major and residual constants A and K remain unproved.",
            "candidate_theorem": "ExplicitGoldbachMajorAndResidualConstants",
            "next_experiment": "Derive independently replayable A and K and test A-K/log(H)-B log(H)^2/sqrt(H)>0 with the now-proved B.",
            "claim_boundary": boundary,
        },
        {
            "problem_id": "twin-prime",
            "ticket_id": "TP-TICKET-126",
            "status": (
                "preregistered_32m_transition_passed_uniform_recurrence_open"
                if twin_pass
                else "frozen_dyadic_candidate_refuted_uniform_route_open"
            ),
            "route": "PreregisteredThirtyTwoMillionDyadicContractionHoldout",
            "proof_or_counterexample_mode": "one-run preregistered falsification of the frozen affine recurrence",
            "attempt": "Evaluate the unchanged alpha=3/4 beta=23/100 certificate endpoint on the first unseen 32M scale.",
            "bounded_result": {"audit_ref": "twin_prime"},
            "obstruction": "One finite transition cannot establish a uniform Vaughan recurrence, between-scale interpolation, parity survival, or exact gap 2.",
            "candidate_theorem": "DyadicVaughanObstructionContractionAndInterpolation",
            "next_experiment": "Use the 32M denominator profile only to falsify coefficient-level recurrence lemmas stated independently of further endpoint data.",
            "claim_boundary": boundary,
        },
    ]


def write_outputs(audit: dict[str, Any]) -> None:
    attempts = build_attempts(audit)
    payload = {
        "schema": SCHEMA,
        "generated_at": GENERATED_AT,
        "status": "route_corrections_and_one_missing_premise_closed_all_conjectures_open",
        "claim_boundary": audit["proof_boundary"],
        "route_correction_audit": audit,
        "attempts": attempts,
    }
    write_json(
        ROOT / "data/open-problem/ticket126-route-correction-audit.json",
        payload,
    )
    paths = {
        "riemann": ROOT
        / "data/open-problem/riemann/rh-ticket-126-autocorrelation-density-no-go.json",
        "collatz": ROOT
        / "data/open-problem/collatz/co-ticket-126-eventually-low-path.json",
        "goldbach": ROOT
        / "data/open-problem/goldbach/gb-ticket-126-prime-power-bound.json",
        "twin-prime": ROOT
        / "data/open-problem/twin-prime/tp-ticket-126-32m-contraction-holdout.json",
    }
    for attempt in attempts:
        write_json(
            paths[attempt["problem_id"]],
            {"schema": SCHEMA, "generated_at": GENERATED_AT, **attempt},
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--execute-holdout",
        action="store_true",
        help="Execute the preregistered 32M holdout exactly once.",
    )
    args = parser.parse_args()
    twin = (
        execute_twin_holdout()
        if args.execute_holdout
        else _load_committed_twin_holdout()
    )
    audit = build_audit(twin)
    if int(audit["machine_audit"]["total_failure_count"]) != 0:
        raise ValueError("TICKET126 machine audit failed")
    write_outputs(audit)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
