from __future__ import annotations

import json
from typing import Any

from ticket30_potential_synthesis_lab import ROOT, read_json, write_json
from ticket43_lift_constraint_measure_lab import FAMILY, build_lift_snapshots
from ticket45_symbolic_rank_clause_lab import (
    CLAUSE_FAMILIES,
    analyze_clause_family,
    compare_clause_extension,
)


GENERATED_AT = "2026-07-08T23:59:00+09:00"
SCHEMA = "primeproject.ticket46-stable-clause-grammar-lab.v1"


def summarize_trial(row: dict[str, Any], extension_27_28: dict[str, Any]) -> dict[str, Any]:
    return {
        "clause_family": row["clause_family"],
        "status": row["status"],
        "clause_count_28": row["clause_count"],
        "pressure_clause_edge_count_28": row["pressure_clause_edge_count"],
        "same_clause_pressure_loop_count_28": row["same_clause_pressure_loop_count"],
        "cycle_detected_28": row.get("pressure_topology", {}).get("cycle_detected"),
        "cyclic_core_node_count_28": row.get("pressure_topology", {}).get("cyclic_core_node_count"),
        "new_clause_count_27_to_28": extension_27_28["new_clause_count"],
        "new_pressure_edge_count_27_to_28": extension_27_28["new_pressure_clause_edge_count"],
        "first_new_pressure_edge_27_to_28": (
            extension_27_28.get("new_pressure_examples") or [None]
        )[0],
    }


def collatz_attempt() -> dict[str, Any]:
    snapshots = build_lift_snapshots(base_bits=12, max_bits=28, checkpoints=(26, 27, 28))
    snapshot_26 = snapshots[26]
    snapshot_27 = snapshots[27]
    snapshot_28 = snapshots[28]
    wrap_stress_trials = [analyze_clause_family(snapshot_28, family) for family in CLAUSE_FAMILIES]
    extension_26_27 = [compare_clause_extension(snapshot_26, snapshot_27, family) for family in CLAUSE_FAMILIES]
    extension_27_28 = [compare_clause_extension(snapshot_27, snapshot_28, family) for family in CLAUSE_FAMILIES]
    ext27_by_family = {row["clause_family"]: row for row in extension_27_28}
    stability_summary = [
        summarize_trial(row, ext27_by_family[row["clause_family"]])
        for row in wrap_stress_trials
    ]
    refuted = [row for row in wrap_stress_trials if "refutes" in row["status"]]
    first_wrap_edge = (
        ext27_by_family["phase_only"].get("new_pressure_examples") or [None]
    )[0]
    exact_summary = next(
        row for row in stability_summary if row["clause_family"] == "phase_tail_residue256_vexact"
    )
    escape_coordinate_audit = [
        {
            "candidate": "unwrapped_phase_epoch",
            "classification": "not_template_local",
            "why_it_is_not_a_proof_yet": (
                "The current template key stores phase modulo 16. An unwrapped epoch must be supplied by the "
                "external lift depth or path history, so it is not a finite horizon-independent clause grammar."
            ),
            "required_next_theorem": (
                "Define a well-founded ordinal or monotone epoch generated by the Collatz transition itself, then "
                "prove every future lift decreases it without rechoosing the epoch from max_bits."
            ),
        },
        {
            "candidate": "depth_or_max_bits_bucket",
            "classification": "horizon_dependent_escape_coordinate",
            "why_it_is_not_a_proof_yet": (
                "A depth bucket can break the observed wrap cycle only because it remembers which bounded horizon "
                "created the edge. A proof needs one fixed object that does not grow when 29, 30, or later bits are "
                "added."
            ),
            "required_next_theorem": (
                "Replace finite depth buckets by a compact transition rule with an invariant descent, or extract a "
                "future edge that refutes that compact rule."
            ),
        },
        {
            "candidate": "exact_observed_template_table",
            "classification": "grows_under_extension_and_is_now_pressure_cyclic",
            "why_it_is_not_a_proof_yet": (
                "The exact template table was a bounded ceiling certificate at 26 bits. At 28 bits it has "
                f"{exact_summary['new_clause_count_27_to_28']} new clauses and "
                f"{exact_summary['new_pressure_edge_count_27_to_28']} new nonnegative-pressure edges, and its "
                "28-bit pressure graph is cyclic."
            ),
            "required_next_theorem": (
                "Either compress the exact table into a stable symbolic grammar with acyclic pressure graph, or "
                "prove an ordinal-valued measure that tolerates the pressure cycles."
            ),
        },
    ]
    return {
        "problem_id": "collatz",
        "ticket_id": "CO-TICKET-46",
        "route": "StableClauseGrammarOrEscapeCoordinateCounteredge",
        "status": "restricted_proof_route_refuted_open_problem_open",
        "proof_or_counterexample_mode": "stable-clause grammar stress test",
        "attempt": (
            "Stress-test every TICKET45 symbolic clause grammar at the first horizon where the modulo-16 phase wrap "
            "is visible. A grammar is discarded if its 28-bit nonnegative-pressure quotient is cyclic. Candidate "
            "repairs that require depth or unwrapped phase are audited as escape coordinates rather than accepted "
            "as proofs."
        ),
        "bounded_result": {
            "source_ticket": "CO-TICKET-45",
            "stable_clause_grammar_audit": {
                "family": FAMILY,
                "max_bits": snapshot_28.max_bits,
                "template_node_count_28": len(snapshot_28.nodes),
                "template_edge_count_28": len(snapshot_28.edges),
                "raw_open_edge_count_28": snapshot_28.raw_open_edge_count,
                "tested_clause_family_count": len(CLAUSE_FAMILIES),
                "refuted_clause_family_count_28": len(refuted),
                "stable_clause_family_count_28": len(CLAUSE_FAMILIES) - len(refuted),
                "wrap_stress_trials_28": wrap_stress_trials,
                "extension_comparisons_26_to_27": extension_26_27,
                "extension_comparisons_27_to_28": extension_27_28,
                "stability_summary": stability_summary,
                "first_phase_wrap_pressure_edge": first_wrap_edge,
                "escape_coordinate_audit": escape_coordinate_audit,
                "restricted_no_go_statement": (
                    "Within the five tested finite template-local scalar clause-rank grammars, no candidate remains "
                    "after 28-bit wrap stress: every tested quotient has a nonnegative-pressure cycle."
                ),
                "closed_bounded_statement": (
                    "The 28-bit lift refutes phase-only, coarse tail mass, residue-16, residue-64, and exact observed "
                    "template scalar clause-rank proof routes by pressure-cycle extraction."
                ),
                "proof_boundary": (
                    "No Collatz proof and no Collatz counterexample. TICKET46 proves only a restricted no-go theorem "
                    "for the tested scalar, template-local clause-rank routes. Surviving approaches must introduce "
                    "a rigorously defined ordinal/stateful measure or find a true Collatz counterexample."
                ),
            },
        },
        "obstruction": (
            "The phase-wrap edge does not merely defeat a coarse quotient. At 28 bits every tested template-local "
            "scalar clause grammar becomes pressure-cyclic, including the exact observed template table. The obvious "
            "repair is to add an epoch/depth coordinate, but that coordinate is horizon-dependent unless a new "
            "well-founded transition theorem is proved."
        ),
        "candidate_theorem": (
            "There exists a compact, horizon-independent ordinal or stateful measure on Collatz lift templates that "
            "strictly decreases on every future lifted open edge, including phase-wrap edges, without rechoosing the "
            "measure at each max_bits."
        ),
        "next_experiment": (
            "Generate TICKET47 by synthesizing ordinal/stateful measures whose state update is template-local and "
            "then extracting a 29-bit or 30-bit counteredge whenever the update secretly depends on horizon depth."
        ),
        "claim_boundary": "No Collatz proof and no certified Collatz counterexample.",
    }


def transfer_attempt(
    source: dict[str, Any],
    problem_id: str,
    ticket_id: str,
    route: str,
    discarded_shortcut: str,
    retained_target: str,
    counterexample_target: str,
    next_experiment: str,
) -> dict[str, Any]:
    prior = next(attempt for attempt in source["attempts"] if attempt["problem_id"] == problem_id)
    return {
        "problem_id": problem_id,
        "ticket_id": ticket_id,
        "status": "proof_pressure_open",
        "route": route,
        "proof_or_counterexample_mode": "stable-clause no-go transfer",
        "attempt": (
            "Transfer TICKET46's rule: a finite symbolic grammar that only works by adding a horizon/depth escape "
            "coordinate cannot be promoted to a proof. It must either become a compact invariant theorem or produce "
            "a genuine counterexample."
        ),
        "bounded_result": {
            "source_ticket": prior["ticket_id"],
            "source_route": prior["route"],
            "discarded_shortcut": discarded_shortcut,
            "retained_target": retained_target,
            "counterexample_target": counterexample_target,
            "ticket46_transfer": route,
        },
        "obstruction": (
            "The project has improved the falsification protocol for proposed proof grammars, but this transfer is "
            "not an infinite proof and not a certified counterexample."
        ),
        "candidate_theorem": retained_target,
        "next_experiment": next_experiment,
        "claim_boundary": f"No {problem_id} proof and no certified {problem_id} counterexample.",
    }


def build_payload() -> dict[str, Any]:
    source = read_json(ROOT / "data/open-problem/ticket45-symbolic-rank-clause-lab.json")
    attempts = [
        transfer_attempt(
            source,
            "riemann",
            "RH-TICKET-46",
            "StableZeroGrammarOrEscapeCoordinateAudit",
            "finite zero grammar repaired by a height-dependent escape coordinate",
            (
                "A compact zero-clause grammar or positive kernel whose margin is invariant under all height "
                "extensions, not reselected from the checked height."
            ),
            "an off-critical zero or kernel-pressure cycle that survives every compact repair",
            "Audit whether zero-feature repairs depend on height; extract the first off-critical pressure cycle.",
        ),
        collatz_attempt(),
        transfer_attempt(
            source,
            "goldbach",
            "GB-TICKET-46",
            "StableMarginGrammarOrExceptionalEscapeAudit",
            "finite residue margin grammar repaired by cutoff-dependent constants",
            (
                "A compact exceptional-residue margin theorem with explicit constants fixed before the cutoff is "
                "extended."
            ),
            "a large even integer or residue class whose pressure edge violates every fixed margin grammar",
            "Audit cutoff-dependent constants and convert them into explicit inequalities or counterexamples.",
        ),
        transfer_attempt(
            source,
            "twin-prime",
            "TP-TICKET-46",
            "StableGapGrammarOrLeakageEscapeAudit",
            "finite exact-gap selector repaired by range-dependent leakage coordinates",
            (
                "A compact gap-2 selector or Maynard-type weight whose positive mass survives every range extension "
                "with fixed parameters."
            ),
            "a leakage pressure cycle where wider gaps absorb every fixed exact-gap selector margin",
            "Audit range-dependent selector repairs and extract the first fixed-parameter leakage cycle.",
        ),
    ]
    return {
        "schema": SCHEMA,
        "generated_at": GENERATED_AT,
        "status": "stable_clause_grammar_restricted_no_go_open_no_resolution",
        "claim_boundary": (
            "Ticket 46 refutes the tested finite scalar clause-rank proof routes and isolates the next ordinal or "
            "stateful-measure obligation. It does not prove or disprove RH, Collatz, Goldbach, or Twin Prime."
        ),
        "attempts": attempts,
    }


def main() -> int:
    payload = build_payload()
    aggregate_path = ROOT / "data/open-problem/ticket46-stable-clause-grammar-lab.json"
    write_json(aggregate_path, payload)
    per_problem_paths = {
        "riemann": ROOT / "data/open-problem/riemann/rh-ticket-46-stable-zero-grammar.json",
        "collatz": ROOT / "data/open-problem/collatz/co-ticket-46-stable-clause-grammar.json",
        "goldbach": ROOT / "data/open-problem/goldbach/gb-ticket-46-stable-margin-grammar.json",
        "twin-prime": ROOT / "data/open-problem/twin-prime/tp-ticket-46-stable-gap-grammar.json",
    }
    for attempt in payload["attempts"]:
        write_json(per_problem_paths[attempt["problem_id"]], attempt)
    print(json.dumps({"written": str(aggregate_path), "schema": SCHEMA, "attempts": len(payload["attempts"])}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
